language: node_js
os: osx
node_js:
  - 10.22.0
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.npm
    - ~/.cache
before_install:
  - pip install --user codecov
after_success:
  - codecov --file .coverage/lcov.info --disable search
install:
  - yarn
script:
  - yarn test
deploy:
  provider: script
  script: sh .scripts/buildAndDeploy.sh
  on:
    branch: master
    tags: true
