language: node_js
os: osx
osx_image: xcode9.3
node_js:
  - 10.22.0
addons:
  chrome: stable
  firefox: "81.0"
  homebrew:
    casks:
      - microsoft-edge
    update: true
cache:
  directories:
    - ~/.npm
    - ~/.cache
before_install:
  - pip install --user codecov
after_success:
  - codecov --file .coverage/lcov.info --disable search
install:
  - yarn
script:
  - yarn test
deploy:
  provider: script
  script: sh .scripts/buildAndDeploy.sh
  on:
    branch: master
    tags: true
