language: node_js
node_js:
- node
before_install:
- pip install --user codecov
after_success:
- codecov --file .coverage/lcov.info --disable search
install:
- yarn install
script:
- yarn test
deploy:
  provider: script
  skip_cleanup: true
  script: sh .travis/pu.sh
  on:
    branch: master
    tags: true